apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: schema-registry
  namespace: factory
spec:
  serviceName: schema-registry-svc
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.3.2
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: 'PLAINTEXT://kafka-cluster:9092'
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8081
  volumeClaimTemplates:
    - metadata:
        name: schema-registry-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
