apiVersion: v1
kind: Service
metadata:
  name: schema-registry-svc
  namespace: factory
spec:
  selector:
    app: schema-registry
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
